name: Layon Ferreira
description: Web developer
meta_description: "Personal website about stuff"
author: Layon Ferreira
markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
relative_url: /
domain_name: 'http://layonferreira.com'
google_analytics: 'UA-58151624-1'
gems: [jekyll-paginate]
#
# # Details for the RSS feed generator
# url:            'blog url'
# author:         'Your Name'
